all: Driver.class Holes.class TakenBlocks.class MemoryAllocations.class StartPointComparator.class
Driver.class: Driver.java
	javac -d . -classpath . Driver.java
Holes.class: Holes.java
	javac -d . -classpath . Holes.java
TakenBlocks.class: TakenBlocks.java
	javac -d . -classpath . TakenBlocks.java
MemoryAllocations.class: MemoryAllocations.java
	javac -d . -classpath . MemoryAllocations.java
StartPointComparator.class: StartPointComparator.java
	javac -d . -classpath . StartPointComparator.java